import { createTheme } from '@vanilla-extract/css'
import { merge } from 'lodash-es'
import { baseTheme } from './base-theme'
import { vars } from './theme-contract.css'

export const dark_theme = createTheme(
  vars,
  merge(baseTheme, {
    color: {
      primary: '#3b82f6',
      primary9: '#eff6ff',
      primary8: '#dbeafe',
      primary7: '#bfdbfe',
      primary6: '#93c5fd',
      primary5: '#60a5fa',
      primary4: '#3b82f6',
      primary3: '#2563eb',
      primary2: '#1d4ed8',
      primary1: '#1e40af',
      primary0: '#1e3a8a',
      success: vars.color.green5,
      success0: vars.color.green1,
      success1: vars.color.green3,
      success2: vars.color.green5,
      success3: vars.color.green7,
      info: vars.color.blue5,
      info0: vars.color.blue1,
      info1: vars.color.blue3,
      info2: vars.color.blue5,
      info3: vars.color.blue7,
      warning: vars.color.yellow5,
      warning0: vars.color.yellow1,
      warning1: vars.color.yellow3,
      warning2: vars.color.yellow5,
      warning3: vars.color.yellow7,
      error: vars.color.red5,
      error0: vars.color.red1,
      error1: vars.color.red3,
      error2: vars.color.red5,
      error3: vars.color.red7,
      border: vars.color.slate7,
      fg_default: vars.color.white,
      fg_default0: vars.color.gray1,
      fg_default1: vars.color.gray2,
      fg_default2: vars.color.gray3,
      fg_default3: vars.color.gray4,
      bg_default: vars.color.gray8,
      bg_default0: vars.color.gray7,
      bg_default1: vars.color.gray6,
      bg_default2: vars.color.gray5,
      bg_default3: vars.color.gray4,
    },
  }),
)
